# syntax=docker/dockerfile:1
ARG BUILDKIT_SBOM_SCAN_CONTEXT=true
ARG BUILDKIT_SBOM_SCAN_STAGE=true

# Shared so the "nagios" account gets the same UID/GID in both stages
ARG NAGIOS_UID=5000
ARG NAGIOS_GID=5000

############################
# Builder: compiles Nagios Core/Plugins/NRPE/NSCA/QStat/NagiosGraph and installs
# everything that needs build tooling. Only the finished artifacts and a computed
# list of their runtime library dependencies are copied into the final stage.
############################
FROM ubuntu:26.04 AS builder

ARG NAGIOS_UID
ARG NAGIOS_GID
ARG NAGIOS_BRANCH=nagios-4.5.14
ARG NAGIOS_PLUGINS_BRANCH=release-2.5
ARG NRPE_BRANCH=nrpe-4.1.3
ARG NSCA_TAG=nsca-2.10.3

ENV NAGIOS_HOME=/opt/nagios
ENV NAGIOS_USER=nagios
ENV NAGIOS_GROUP=nagios
ENV NAGIOS_CMDUSER=nagios
ENV NAGIOS_CMDGROUP=nagios
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update && \
    apt-get -qq -y install --no-install-recommends software-properties-common && \
    add-apt-repository universe && \
    apt-get -qq update && \
    apt-get -qq -y install --no-install-recommends \
        apache2 \
        autoconf \
        automake \
        build-essential \
        ca-certificates \
        freetds-dev \
        gettext \
        git \
        gperf \
        libcgi-pm-perl \
        libdbi-dev \
        libfreeradius-dev \
        libradsec-dev \
        libgd-dev \
        libgd-gd2-perl \
        libldap2-dev \
        libmariadb-dev \
        libnagios-object-perl \
        libpq-dev \
        libpython3-dev \
        librrds-perl \
        libssl-dev \
        libxpm-dev \
        m4 \
        python3-full \
        python3-pip \
        unzip && \
    apt-get -qq -y purge --auto-remove software-properties-common && \
    apt-get -qq clean && \
    rm -rf /var/lib/apt/lists/* && \
    # Reduce unecesssary git output
    git config --global advice.detachedHead false

RUN ( grep -Ei "^${NAGIOS_GROUP}"    /etc/group || groupadd --gid ${NAGIOS_GID} $NAGIOS_GROUP ) && \
    ( grep -Ei "^${NAGIOS_CMDGROUP}" /etc/group || groupadd $NAGIOS_CMDGROUP )
RUN ( id -u $NAGIOS_USER    || useradd --system --uid ${NAGIOS_UID} -d $NAGIOS_HOME -g $NAGIOS_GROUP    $NAGIOS_USER ) && \
    ( id -u $NAGIOS_CMDUSER || useradd --system -d $NAGIOS_HOME -g $NAGIOS_CMDGROUP $NAGIOS_CMDUSER )

RUN update-ca-certificates -f

# Install Nagios Core
RUN cd /tmp && \
    git clone --depth 1 https://github.com/NagiosEnterprises/nagioscore.git -b ${NAGIOS_BRANCH} && \
    cd nagioscore && \
    cp /usr/share/misc/config.* . && \
    ./configure \
        --prefix=${NAGIOS_HOME} \
        --exec-prefix=${NAGIOS_HOME} \
        --enable-event-broker \
        --with-command-user=${NAGIOS_CMDUSER} \
        --with-command-group=${NAGIOS_CMDGROUP} \
        --with-nagios-user=${NAGIOS_USER} \
        --with-nagios-group=${NAGIOS_GROUP} && \
    make all && \
    make install && \
    make install-config && \
    make install-commandmode && \
    make install-webconf && \
    make clean && \
    cd /tmp && rm -Rf nagioscore

# Install Nagios Plugins
RUN cd /tmp && \
    git clone --depth 1 https://github.com/nagios-plugins/nagios-plugins.git -b $NAGIOS_PLUGINS_BRANCH && \
    cd nagios-plugins && \
    ./tools/setup && \
    ./configure \
        --prefix=${NAGIOS_HOME} \
        --with-ipv6 \
        --with-ping-command="/usr/bin/ping -n -U -W %d -c %d %s" \
        --with-ping6-command="/usr/bin/ping -6 -n -U -W %d -c %d %s" && \
    make && \
    make install && \
    make clean && \
    mkdir -p /usr/lib/nagios/plugins && \
    ln -sf ${NAGIOS_HOME}/libexec/utils.pm /usr/lib/nagios/plugins && \
    chown root:root ${NAGIOS_HOME}/libexec/check_icmp && \
    chmod u+s ${NAGIOS_HOME}/libexec/check_icmp && \
    cd /tmp && rm -Rf nagios-plugins 

# Install NRPE
RUN cd /tmp && \
    git clone --depth 1 https://github.com/NagiosEnterprises/nrpe.git -b ${NRPE_BRANCH} && \
    cd nrpe && \
    ./configure && \
    make check_nrpe > /dev/null && \
    cp src/check_nrpe ${NAGIOS_HOME}/libexec/ && \
    make clean && \
    cd /tmp && rm -Rf nrpe

# Install NagiosGraph
RUN cd /tmp && \
    git clone --depth 1 https://git.code.sf.net/p/nagiosgraph/git nagiosgraph && \
    cd nagiosgraph && \
    ./install.pl --install \
        --prefix /opt/nagiosgraph \
        --nagios-user ${NAGIOS_USER} \
        --www-user ${NAGIOS_USER} \
        --nagios-perfdata-file ${NAGIOS_HOME}/var/perfdata.log \
        --nagios-cgi-url /cgi-bin && \
    cp share/nagiosgraph.ssi ${NAGIOS_HOME}/share/ssi/common-header.ssi && \
    cd /tmp && rm -Rf nagiosgraph

# Install NSCA
RUN cd /tmp && \
    git clone --depth 1 --branch ${NSCA_TAG} https://github.com/NagiosEnterprises/nsca.git && \
    cd nsca && \
    ./configure \
        --prefix=${NAGIOS_HOME} \
        --with-nsca-user=${NAGIOS_USER} \
        --with-nsca-grp=${NAGIOS_GROUP} && \
    make all && \
    cp src/nsca ${NAGIOS_HOME}/bin/ && \
    cp src/send_nsca ${NAGIOS_HOME}/bin/ && \
    cp sample-config/nsca.cfg ${NAGIOS_HOME}/etc/ && \
    cp sample-config/send_nsca.cfg ${NAGIOS_HOME}/etc/ && \
    sed -i 's/^#server_address.*/server_address=0.0.0.0/'  ${NAGIOS_HOME}/etc/nsca.cfg && \
    cd /tmp && rm -Rf nsca

# Install QStat
RUN cd /tmp && \
    git clone --depth 1 https://github.com/multiplay/qstat.git && \
    cd qstat && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install && \
    make clean && \
    cd /tmp && rm -Rf qstat

# Install additional plugins (pip packages land in a fixed path, independent of the Python version)
RUN mkdir -p /opt/nagios-pyplugins && \
    cd /opt && \
    pip3 install --break-system-packages --no-cache-dir --target=/opt/nagios-pyplugins pymssql && \
    pip3 install --break-system-packages --no-cache-dir --target=/opt/nagios-pyplugins --find-links https://wheel-index.linuxserver.io/ubuntu/ pywbem paramiko pplogger paho-mqtt && \
    pip3 install --break-system-packages --no-cache-dir --target=/opt/nagios-pyplugins --find-links https://wheel-index.linuxserver.io/ubuntu/ --upgrade requests && \
    git clone --depth 1 https://github.com/willixix/naglio-plugins.git WL-Nagios-Plugins && \
    git clone --depth 1 https://github.com/JasonRivers/nagios-plugins.git JR-Nagios-Plugins && \
    git clone --depth 1 https://github.com/justintime/nagios-plugins.git JE-Nagios-Plugins && \
    git clone --depth 1 https://github.com/nagiosenterprises/check_mssql_collection.git nagios-mssql && \
    git clone --depth 1 https://github.com/danfruehauf/nagios-plugins.git DF-Nagios-Plugins && \
    git clone --depth 1 https://github.com/jpmens/check-mqtt.git jpmens-mqtt && \
    chmod +x /opt/WL-Nagios-Plugins/check* && \
    chmod +x /opt/JE-Nagios-Plugins/check_mem/check_mem.pl && \
    chmod +x /opt/DF-Nagios-Plugins/check_sql/check_sql && \
    chmod +x /opt/DF-Nagios-Plugins/check_jenkins/check_jenkins && \
    chmod +x /opt/DF-Nagios-Plugins/check_vpn/check_vpn && \
    chmod +x /opt/jpmens-mqtt/check-mqtt.py && \
    cp /opt/JE-Nagios-Plugins/check_mem/check_mem.pl ${NAGIOS_HOME}/libexec/ && \
    cp /opt/nagios-mssql/check_mssql_database.py ${NAGIOS_HOME}/libexec/ && \
    cp /opt/nagios-mssql/check_mssql_server.py ${NAGIOS_HOME}/libexec/ && \
    cp /opt/DF-Nagios-Plugins/check_sql/check_sql ${NAGIOS_HOME}/libexec/ && \
    cp /opt/DF-Nagios-Plugins/check_jenkins/check_jenkins ${NAGIOS_HOME}/libexec/ && \
    cp /opt/DF-Nagios-Plugins/check_vpn/check_vpn ${NAGIOS_HOME}/libexec/ && \
    cp /opt/jpmens-mqtt/check-mqtt.py ${NAGIOS_HOME}/libexec/ && \
    find /opt -maxdepth 2 -type d -name .git -exec rm -rf {} +

# Add check_apc.pl check
COPY plugins/check_apc.pl ${NAGIOS_HOME}/libexec/
RUN chmod +x ${NAGIOS_HOME}/libexec/check_apc.pl

# Discover the runtime shared-library packages actually linked by everything just
# built, so the final stage can install those instead of the full -dev packages.
RUN { find "${NAGIOS_HOME}/bin" "${NAGIOS_HOME}/sbin" "${NAGIOS_HOME}/libexec" -type f -perm -u+x; \
      find /usr/local/bin -maxdepth 1 -type f -perm -u+x; \
      find /opt/nagios-pyplugins -type f -name '*.so'; \
    } 2>/dev/null | sort -u | xargs -r -I{} ldd {} 2>/dev/null \
      | awk '{print $3}' | grep '^/' | sort -u \
      | xargs -r dpkg -S 2>/dev/null | cut -d: -f1 | sort -u > /runtime-packages.txt || true

############################
# Final image: runtime-only packages plus the artifacts copied from the builder
############################
FROM ubuntu:26.04

LABEL name="Nagios"
LABEL nagiosVersion="4.5.14"
LABEL nagiosPluginsVersion="2.5"
LABEL nrpeVersion="4.1.3"
LABEL nscaVersion="2.10.3"
LABEL ncpaVersion="3.4.3"
LABEL nagiostvVersion="0.9.11"
LABEL homepage="https://www.nagios.com/"
LABEL maintainer="Tronyx <tronyx@tronflix.app>"

ARG NAGIOS_UID
ARG NAGIOS_GID
ARG NCPA_BRANCH=v3.4.3
ARG NAGIOSTV_VERSION=0.9.11

# Environment variables
ENV NAGIOS_HOME=/opt/nagios
ENV NAGIOS_USER=nagios
ENV NAGIOS_GROUP=nagios
ENV NAGIOS_CMDUSER=nagios
ENV NAGIOS_CMDGROUP=nagios
ENV NAGIOS_FQDN=nagios.example.com
ENV NAGIOSADMIN_USER=nagiosadmin
ENV NAGIOSADMIN_PASS=nagios
ENV APACHE_RUN_USER=nagios
ENV APACHE_RUN_GROUP=nagios
ENV APACHE_LOCK_DIR=/var/run
ENV APACHE_LOG_DIR=/var/log/apache2
ENV NAGIOS_TIMEZONE=UTC
ENV DEBIAN_FRONTEND=noninteractive
ENV NG_CGI_URL=/cgi-bin
ENV NG_NAGIOS_CONFIG_FILE=${NAGIOS_HOME}/etc/nagios.cfg
ENV NG_CGI_DIR=${NAGIOS_HOME}/sbin
ENV NG_WWW_DIR=${NAGIOS_HOME}/share/nagiosgraph
ENV PYTHONPATH=/opt/nagios-pyplugins

COPY --from=builder /runtime-packages.txt /runtime-packages.txt
RUN echo postfix postfix/main_mailer_type string "'Internet Site'" | debconf-set-selections && \
    echo postfix postfix/mynetworks string "127.0.0.0/8" | debconf-set-selections && \
    echo postfix postfix/mailname string ${NAGIOS_FQDN} | debconf-set-selections && \
    apt-get -qq update && \
    apt-get -qq -y install --no-install-recommends software-properties-common && \
    add-apt-repository universe && \
    apt-get -qq update && \
    apt-get -qq -y install --no-install-recommends \
        $(cat /runtime-packages.txt) \
        apache2 \
        apache2-utils \
        bc \
        bsd-mailx \
        ca-certificates \
        curl \
        dnsutils \
        fping \
        gettext \
        iputils-ping \
        jq \
        libapache2-mod-php \
        libcache-memcached-perl \
        libcgi-pm-perl \
        libcrypt-des-perl \
        libcrypt-rijndael-perl \
        libcrypt-x509-perl \
        libdbd-mysql-perl \
        libdbd-pg-perl \
        libdbi-perl \
        libdigest-hmac-perl \
        libgd-gd2-perl \
        libjson-perl \
        libnagios-object-perl \
        libmonitoring-plugin-perl \
        libnet-snmp-perl \
        libnet-tftp-perl \
        libnet-xmpp-perl \
        libredis-perl \
        librrds-perl \
        libswitch-perl \
        libtext-glob-perl \
        libwww-perl \
        netcat-traditional \
        openssh-client \
        parallel \
        php-cli \
        php-gd \
        postfix \
        python3-full \
        python3-nagiosplugin \
        rsync \
        rsyslog \
        runit \
        smbclient \
        snmp \
        snmpd \
        snmp-mibs-downloader \
        unzip \
        xinetd && \
    apt-get -qq -y purge --auto-remove software-properties-common && \
    apt-get -qq clean && \
    rm -rf /var/lib/apt/lists/* /runtime-packages.txt

RUN ( grep -Ei "^${NAGIOS_GROUP}"    /etc/group || groupadd --gid ${NAGIOS_GID} $NAGIOS_GROUP ) && \
    ( grep -Ei "^${NAGIOS_CMDGROUP}" /etc/group || groupadd $NAGIOS_CMDGROUP )
RUN ( id -u $NAGIOS_USER    || useradd --system --uid ${NAGIOS_UID} -d $NAGIOS_HOME -g $NAGIOS_GROUP    $NAGIOS_USER ) && \
    ( id -u $NAGIOS_CMDUSER || useradd --system -d $NAGIOS_HOME -g $NAGIOS_CMDGROUP $NAGIOS_CMDUSER )

RUN update-ca-certificates -f

# Copy the compiled Nagios stack and plugins from the builder stage
COPY --from=builder ${NAGIOS_HOME} ${NAGIOS_HOME}
COPY --from=builder /opt/nagiosgraph /opt/nagiosgraph
COPY --from=builder /opt/nagios-pyplugins /opt/nagios-pyplugins
COPY --from=builder /opt/WL-Nagios-Plugins /opt/WL-Nagios-Plugins
COPY --from=builder /opt/JR-Nagios-Plugins /opt/JR-Nagios-Plugins
COPY --from=builder /opt/JE-Nagios-Plugins /opt/JE-Nagios-Plugins
COPY --from=builder /opt/nagios-mssql /opt/nagios-mssql
COPY --from=builder /opt/DF-Nagios-Plugins /opt/DF-Nagios-Plugins
COPY --from=builder /opt/jpmens-mqtt /opt/jpmens-mqtt
COPY --from=builder /usr/lib/nagios/plugins /usr/lib/nagios/plugins
COPY --from=builder /usr/local/bin/qstat /usr/local/bin/qstat

# Install NCPA
RUN wget -q -O ${NAGIOS_HOME}/libexec/check_ncpa.py https://raw.githubusercontent.com/NagiosEnterprises/ncpa/${NCPA_BRANCH}/client/check_ncpa.py && \
    chmod +x ${NAGIOS_HOME}/libexec/check_ncpa.py

# Install NagiosTV
RUN cd /tmp && \
    wget -q https://github.com/chriscareycode/nagiostv-react/releases/download/v${NAGIOSTV_VERSION}/nagiostv-${NAGIOSTV_VERSION}.tar.gz && \
    tar xf nagiostv-${NAGIOSTV_VERSION}.tar.gz -C /opt/nagios/share/ && \
    rm /tmp/nagiostv-${NAGIOSTV_VERSION}.tar.gz

RUN sed -i.bak 's/.*\=www\-data//g' /etc/apache2/envvars

RUN export DOC_ROOT="DocumentRoot ${NAGIOS_HOME}/share" && \
    sed -i "s,DocumentRoot.*,${DOC_ROOT}," /etc/apache2/sites-enabled/000-default.conf && \
    sed -i "s,</VirtualHost>,<IfDefine ENABLE_USR_LIB_CGI_BIN>\nScriptAlias /cgi-bin/ ${NAGIOS_HOME}/sbin/\n</IfDefine>\n</VirtualHost>," /etc/apache2/sites-enabled/000-default.conf && \
    ln -s /etc/apache2/mods-available/cgi.load /etc/apache2/mods-enabled/cgi.load

RUN mkdir -p -m 0755 /usr/share/snmp/mibs && \
    mkdir -p ${NAGIOS_HOME}/etc/conf.d && \
    mkdir -p ${NAGIOS_HOME}/etc/monitor && \
    mkdir -p -m 700  ${NAGIOS_HOME}/.ssh && \
    chown ${NAGIOS_USER}:${NAGIOS_GROUP} ${NAGIOS_HOME}/.ssh && \
    touch /usr/share/snmp/mibs/.foo && \
    ln -s /usr/share/snmp/mibs ${NAGIOS_HOME}/libexec/mibs && \
    ln -s ${NAGIOS_HOME}/bin/nagios /usr/local/bin/nagios && \
    download-mibs && echo "mibs +ALL" > /etc/snmp/snmp.conf

RUN sed -i 's,/bin/mail,/usr/bin/mail,' ${NAGIOS_HOME}/etc/objects/commands.cfg && \
    sed -i 's,/usr/usr,/usr,' ${NAGIOS_HOME}/etc/objects/commands.cfg

RUN postfix check && \
    cp /etc/services /var/spool/postfix/etc/ && \
    echo "smtp_address_preference = ipv4" >> /etc/postfix/main.cf

RUN rm -rf /etc/rsyslog.d /etc/rsyslog.conf /etc/sv/getty-5

ADD overlay /

RUN echo "use_timezone=${NAGIOS_TIMEZONE}" >> ${NAGIOS_HOME}/etc/nagios.cfg

# Copy example config in-case the user has started with empty var or etc
RUN mkdir -p /orig/var && \
    mkdir -p /orig/etc && \
    mkdir -p /orig/graph-etc && \
    mkdir -p /orig/graph-var && \
    mkdir -p /orig/xinetd.d && \
    cp -Rp ${NAGIOS_HOME}/var/* /orig/var/ && \
    cp -Rp ${NAGIOS_HOME}/etc/* /orig/etc/ && \
    cp -Rp /opt/nagiosgraph/etc/* /orig/graph-etc && \
    cp -Rp /opt/nagiosgraph/var/* /orig/graph-var && \
    cp -Rp /etc/xinetd.d/* /orig/xinetd.d/

## Set the permissions for example config
RUN find /opt/nagios/etc \! -user ${NAGIOS_USER} -exec chown ${NAGIOS_USER}:${NAGIOS_GROUP} '{}' + && \
    find /orig/etc \! -user ${NAGIOS_USER} -exec chown ${NAGIOS_USER}:${NAGIOS_GROUP} '{}' +

RUN a2enmod session && \
    a2enmod session_cookie && \
    a2enmod session_crypto && \
    a2enmod auth_form && \
    a2enmod request

# Make scripts executable
RUN chmod +x /usr/local/bin/start_nagios && \
    chmod +x /etc/sv/*/run && \
    chmod +x /opt/nagiosgraph/etc/fix-nagiosgraph-multiple-selection.sh

RUN cd /opt/nagiosgraph/etc && \
    sh fix-nagiosgraph-multiple-selection.sh

# Enable all runit services
RUN ln -sf /etc/sv/* /etc/service

# Fix ping permissions for Nagios user
RUN chmod u+s /usr/bin/ping

# Set ServerName and timezone for Apache
RUN echo "ServerName ${NAGIOS_FQDN}" > /etc/apache2/conf-available/servername.conf && \
    echo "PassEnv TZ" > /etc/apache2/conf-available/timezone.conf && \
    ln -s /etc/apache2/conf-available/servername.conf /etc/apache2/conf-enabled/servername.conf && \
    ln -s /etc/apache2/conf-available/timezone.conf /etc/apache2/conf-enabled/timezone.conf

# Cleanup
# Remove unecessary packages after install/setup are complete
RUN apt-get -qq -y autoremove && \
    # Remove dirs from git clones, cache, etc.
    rm -rf /root/.cache \
    /tmp/* \
    /var/lib/apt/lists/* && \
    # Remove some other files and dirs
    rm -f /opt/nagiosgraph/etc/fix-nagiosgraph-multiple-selection.sh \
    /opt/get-pip.py \
    /var/lib/dpkg/status-old && \
    true > /var/log/dpkg.log && \
    true > /var/log/lastlog && \
    true > /var/log/apt/term.log

# Expose port 80 for the web UI
EXPOSE 80 5667

# Specify volumes
VOLUME "${NAGIOS_HOME}/var" "${NAGIOS_HOME}/etc" "/var/log/apache2" "/opt/Custom-Nagios-Plugins" "/opt/nagiosgraph/var" "/opt/nagiosgraph/etc"

# Start command
CMD [ "/usr/local/bin/start_nagios" ]
