#!/bin/bash

echo 'Checking permissions for nagios & nagiosgraph...'
# libexec is skipped so chown doesn't strip the setuid root bit from check_icmp
find /opt/nagios -path /opt/nagios/libexec -prune -o \! -user "${NAGIOS_USER}" -exec chown "${NAGIOS_USER}":"${NAGIOS_GROUP}" '{}' +
find /opt/nagiosgraph \! -user "${NAGIOS_USER}" -exec chown "${NAGIOS_USER}":"${NAGIOS_GROUP}" '{}' +

if ! [ -f /opt/nagiosgraph/etc/ngshared.pm ]; then
    echo "ngshared.pm missing from /opt/nagiosgraph/etc, restoring the image default..."
    cp -p /orig/graph-etc/ngshared.pm /opt/nagiosgraph/etc/
fi

exec "${NAGIOS_HOME}/bin/nagios" "${NAGIOS_HOME}/etc/nagios.cfg"
